name: "utool plugin pack"
description: "打包 utools 插件"
inputs:
  dir: # 输入 id
    description: "打包路径"
    required: false
    default: "./"
  filename:
    description: "文件名"
    required: false
    default: ""
  tag_name: # 输入 id
    description: "版本标签"
    required: true
  output_dir:
    description: "输出文件夹"
    required: false
    default: "./"
  upload_url:
    description: "上传链接"
    required: true
outputs:
  filepath: # 输出 id
    description: "打包输出的文件名"
runs:
  using: "node12"
  main: "dist/index.js"
