on:
  release:
    types: [created]
name: build chrome history
jobs:
  pack:
    name: pack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - uses: actions/download-artifact@v1
        with:
          name: search_windows.exe
      - uses: actions/download-artifact@v1
        with:
          name: search_linux
      - uses: actions/download-artifact@v1
        with:
          name: search_darwin
      - run: ls -alh && mv search_*/* chrome-history/
      - name: pack chrome-history
        uses: mohuishou/utools/.github/action@master
        id: chromeHistory
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          dir: ./plugins/chrome-history
          upload_url: ${{ github.event.release.upload_url }}
