on:
  release:
    types: [created]
name: chrome-history
jobs:
  pack:
    name: pack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: build
        run: |
          cd plugins/chrome-history
          yarn
          tsc
      - name: pack chrome-history
        uses: mohuishou/utools/.github/action@master
        id: chromeHistory
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          dir: ./plugins/chrome-history
          upload_url: ${{ github.event.release.upload_url }}
