on:
  release:
    types: [created]
name: vedio-parse
jobs:
  pack:
    name: pack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: install node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: build
        run: |
          cd plugins/vedio-parse
          yarn
          tsc
      - name: pack vedio-parse
        uses: mohuishou/utools/.github/action@master
        id: vedio-parse
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          dir: ./plugins/vedio-parse
          upload_url: ${{ github.event.release.upload_url }}
