on:
  release:
    types: [created]
name: build yuque
jobs:
  pack:
    name: pack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: install node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: build
        run: |
          cd plugins/yuque
          echo "{\"client_id\":\"${{ secrets.client_id }}\",\"client_secret\":\"${{ secrets.client_secret }}\"}" >& config.json
          yarn
          tsc
      - name: pack yuque
        uses: mohuishou/utools/.github/action@master
        id: yuque
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          dir: ./plugins/yuque
          upload_url: ${{ github.event.release.upload_url }}
